# Build and JAR files or such and copy to artifacts folder
# Copy Git files to artifacts folder
# Deploy the ARM template
# 

trigger: none

parameters:
# This is the path of your notebooks in Git.  Currently, this is not recursively deploying notebooks
- name: GIT_NOTEBOOK_PATH
  displayName: Notebooks Relative Path in Git
  type: string
  default: 'notebooks/MyProject'

# This is where in your Databricks workspace your notebooks will be deployed
# Typically this is under a Folder under the Workspace and not under a specific user's folder
- name: NOTEBOOK_DEPLOYMENT_PATH
  displayName: Notebooks Deployment Path to Databricks
  type: string
  default: '/MyProject'

# This resource group for the Databricks workspace and KeyVault
- name: RESOURCE_GROUP
  displayName: Resource Group Name
  type: string
  default: 'Databricks-MyProject'

# The Azure region to which to deploy your resources
- name: LOCATION
  displayName: Azure Region
  type: string
  default: 'EastUS2'
  values:
  - EastUS
  - EastUS2
  - Add-others-here

# This is the name of your Azure Databricks resrouce
- name: WORKSPACE_NAME
  displayName: Databricks workspace name
  type: string
  default: 'Databricks-MyProject'

# This is a KeyVault for holding the Service Principal to make Databricks API calls and to hold Databricks KeyVault backed Secrets
- name: KEY_VAULT_NAME
  displayName: KeyVault name
  type: string
  default: 'KeyVault-MyProject'

# This is the subscription the Databricks workspace and KeyVault will be created in
- name: SUBSCRIPTION_ID
  displayName: Azure Subscription Id
  type: string
  default: '00000000-0000-0000-0000-000000000000'

  # NOTE: You could make this a variable and then change the name to append the environment parameter above.  You would need to create a corrisponding service connection
  # e.g. If you connection is named "MyConnection", you would have MyConnection-Dev (for dev subscription), MyConnection-QA (etc...)
- name: RESOURCE_MANAGER_CONNECTION
  displayName: Azure Resource Connection Name
  type: string
  default: 'Microsoft Azure Adam Paternostro(00000000-0000-0000-0000-000000000000)'


stages:
#############################################################
# Build the code
# Currently this is not building and JAR files, but you would do that here
# This is packaging up the files from Git to the Artifacts files
#############################################################
- stage: Build
  jobs:
  - job: JobBuild
    displayName: 'Job Build'
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: ARM-Templates'
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)/ARM-Templates'
          ArtifactName: 'ARM-Templates'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Databricks-Clusters'
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)/clusters'
          ArtifactName: 'clusters'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Databricks-Notebooks'
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)/notebooks'
          ArtifactName: 'notebooks'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Databricks-Init-Scripts'
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)/init-scripts'
          ArtifactName: 'init-scripts'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Databricks-Deployment-Scripts'
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)/deployment-scripts'
          ArtifactName: 'deployment-scripts'


#############################################################
# Deploy to Dev
#############################################################
- stage: Staging
  jobs:
  - deployment: JobDev
    displayName: 'Job Dev'
    environment: 'Dev'
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:  
          steps:
            - checkout: none

            ### Show all the environment variables ###
            - task: PowerShell@2
              displayName: "Current Environment Variables"
              inputs:
                targetType: 'inline'
                script: 'dir env:'

            ### Deploy Databricks Workspace ###
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: "Deploy Databricks ARM Template"
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: ${{ parameters.RESOURCE_MANAGER_CONNECTION}}
                subscriptionId: ${{ parameters.SUBSCRIPTION_ID }}
                action: 'Create Or Update Resource Group'
                resourceGroupName: ${{ parameters.RESOURCE_GROUP }}-Dev
                location: ${{ parameters.LOCATION }}
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)/ARM-Templates/azuredeploy.databricks.json'
                csmParametersFile: '$(Pipeline.Workspace)/ARM-Templates/parameters.databricks.json'
                overrideParameters: '-workspaceName ${{ parameters.WORKSPACE_NAME }}-Dev'
                deploymentMode: 'Incremental'

            ### Show Azure KeyVault ###
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: "Deploy KeyVault ARM Template"
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: ${{ parameters.RESOURCE_MANAGER_CONNECTION}}
                subscriptionId: ${{ parameters.SUBSCRIPTION_ID }}
                action: 'Create Or Update Resource Group'
                resourceGroupName: ${{ parameters.RESOURCE_GROUP }}-Dev
                location: ${{ parameters.LOCATION }}
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)/ARM-Templates/azuredeploy.keyvault.json'
                csmParametersFile: '$(Pipeline.Workspace)/ARM-Templates/parameters.keyvault.json'
                overrideParameters: '-keyVaultName ${{ parameters.KEY_VAULT_NAME }}-Dev'
                deploymentMode: 'Incremental'

            ### Download KeyVault Secrests ###
            - task: AzureKeyVault@1
              displayName: "Download KeyVault Secrets"
              inputs:
                azureSubscription: ${{ parameters.RESOURCE_MANAGER_CONNECTION}}
                KeyVaultName:  '${{ parameters.KEY_VAULT_NAME }}-Dev'
                SecretsFilter: 'databricks-dev-ops-subscription-id,databricks-dev-ops-tenant-id,databricks-dev-ops-client-id,databricks-dev-ops-client-secret'
                RunAsPreJob: false

            ### Deploy your Databricks Init Scripts to dbfa:/init-scripts folder on DBFS ###
            - task: Bash@3
              displayName: "Deploy Databricks Init Scripts"
              # Only run if KeyVault has values set
              # condition: ne($(databricks-dev-ops-tenant-id), 'PLEASE_SET_ME (e.g. 00000000-0000-0000-0000-000000000000)')
              inputs:
                filePath: '$(Pipeline.Workspace)/deployment-scripts/deploy-init-scripts.sh'
                arguments: '$(databricks-dev-ops-tenant-id) $(databricks-dev-ops-client-id) $(databricks-dev-ops-client-secret) $(databricks-dev-ops-subscription-id) ${{ parameters.RESOURCE_GROUP }}-Dev ${{ parameters.WORKSPACE_NAME }}-Dev'
                workingDirectory: '$(Pipeline.Workspace)/init-scripts'

            ### Deploy your Databricks Clusters (and then Stop them since a deployment starts them) ###
            - task: Bash@3
              displayName: "Deploy Databricks Clusters"
              # Only run if KeyVault has values set
              # condition: ne($(databricks-dev-ops-tenant-id), 'PLEASE_SET_ME (e.g. 00000000-0000-0000-0000-000000000000)')
              inputs:
                filePath: '$(Pipeline.Workspace)/deployment-scripts/deploy-clusters.sh'
                arguments: '$(databricks-dev-ops-tenant-id) $(databricks-dev-ops-client-id) $(databricks-dev-ops-client-secret) $(databricks-dev-ops-subscription-id) ${{ parameters.RESOURCE_GROUP }}-Dev ${{ parameters.WORKSPACE_NAME }}-Dev'
                workingDirectory: '$(Pipeline.Workspace)/clusters'

            ### Deploy your Databricks Notebooks ###
            - task: Bash@3
              displayName: "Deploy Databricks Notebooks"
              # Only run if KeyVault has values set
              # condition: ne($(databricks-dev-ops-tenant-id), 'PLEASE_SET_ME (e.g. 00000000-0000-0000-0000-000000000000)')
              inputs:
                filePath: '$(Pipeline.Workspace)/deployment-scripts/deploy-notebooks.sh'
                arguments: '$(databricks-dev-ops-tenant-id) $(databricks-dev-ops-client-id) $(databricks-dev-ops-client-secret) $(databricks-dev-ops-subscription-id) ${{ parameters.RESOURCE_GROUP }}-Dev ${{ parameters.WORKSPACE_NAME }}-Dev ${{ parameters.NOTEBOOK_DEPLOYMENT_PATH }}'
                workingDirectory: '$(Pipeline.Workspace)/${{ parameters.GIT_NOTEBOOK_PATH }}'
