name: Databricks-CI-CD

# Manual trigger with parameters
on:
  workflow_dispatch:
    inputs:
      GIT_NOTEBOOK_PATH:
        description: 'Notebooks Relative Path in Git'
        required: true
        default: 'notebooks/MyProject'
           

jobs:
  build:
    runs-on: ubuntu-latest

    # Checkout code
    steps:
    - uses: actions/checkout@v2

    # Show the environment variables for debuggin
    - name: Display Environment Variable
      uses: azure/powershell@v1
      with:
        inlineScript: |
          dir env:
        azPSVersion: '3.1.0'

    # Publish Artifact: ARM-Templates
    - name: 'Publish Artifact: ARM-Templates' 
      uses: actions/upload-artifact@v2
      with:
        name: 'ARM-Templates'
        path: '$HOME/ARM-Templates'           
